### ISSUE TITLE
Can not compile : XvAbletonLink does not exist

### ISSUE THREAD

**Issue by kvacquier** [jasonjsnell/ABLLinkSwiftWrapper#1]
Hello. I can not compile : XvAbletonLink LinkKitTest/LinkKitTest/LinkWrapper.swift:470:33: Use of undeclared type 'XvAbletonLink'

**Comment by jasonjsnell** [comment]
Ah thanks for catching that. XvAbletonLink was the class name on a previous version. I updated it to be the current class name, LinkWrapper. Let me know if that works now for you.

**Comment by kvacquier** [comment]
worked nice.
